Repository hmcts/lau-frontend, pull requests merged in 2022-04, with the labels that each got.

#50 LAU-368 Cookie manager update
  package.json
  src/main/assets/js/cookie.ts
  src/main/assets/scss/main.scss
  src/main/views/common/template.njk
  src/main/views/cookies/content.ts
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-50

#51 LAU-368 Cookie manager update
  package.json
  src/main/assets/js/cookie.ts
  src/main/views/common/template.njk
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-51

#48 LAU-346 Add feature toggle for Flatpickr preload
  package.json
  src/main/routes/home.ts
  src/main/views/common/template.njk
  src/main/views/common/webpack/css-template.njk
  src/main/views/common/webpack/css.njk
  src/test/end-to-end/paths/logonPage.js
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-48

#54 LAU-371: Fix dependency check issue.
  package.json
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-54

#55 LAU-372: Dependency fixes
  package.json
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-55

#24 LAU-273 lau-session cookie set to secure
  bin/githooks/pre-commit
  src/main/modules/session/index.ts
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-24
