Repository hmcts/lau-frontend, pull requests merged in 2022-12, with the labels that each got.

#109 LAU-563 Upgrade Terrafrom
  infrastructure/.terraform-version
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-109

#107 LAU-561 Rework Docker build following Yarn v3 upgrade
  .dockerignore
  .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  .yarnrc.yml
  Dockerfile
  package.json
  src/main/models/Logs.ts
  yarn.lock
Labels: ns:lau, prd:lau, keep-helm, rel:lau-frontend-pr-107

#115 LAU-578: Fix frontend mutation tests
  package.json
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-115
