Repository hmcts/lau-frontend, pull requests merged in 2022-08, with the labels that each got.

#79 LAU-482 Security scan fix
  audit.json
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-79

#81 LAU-480 Adjust functional tests for stability
  package.json
  src/test/config.js
  src/test/end-to-end/lauApi/lauHelper.js
  src/test/end-to-end/pages/IDAM/signIn.js
  src/test/end-to-end/paths/homePageLau.js
  src/test/end-to-end/paths/logonPage.js
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-81

#83 Add backstage configuration file
  catalog-info.yaml
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-83
