Repository hmcts/lau-frontend, pull requests merged in 2022-03, with the labels that each got.

#41 Update nodejs chart to 2.4.1
  charts/lau-frontend/Chart.yaml
  package.json
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-41

#42 LAU-319 Performance improvements
  package.json
  src/main/app.ts
  src/main/modules/helmet/index.ts
  src/main/modules/nunjucks/index.ts
  src/main/views/common/webpack/css-template.njk
  src/main/views/common/webpack/css.njk
  src/main/views/common/webpack/js-template.njk
  src/main/views/common/webpack/js.njk
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-42

#38 Add pre-commit hook to bump patch version
  bin/githooks/pre-commit
  bin/preinstall.sh
  package.json
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-38

#45 Integrate codeceptJS framework with the existing lau-frontend repo
  .eslintignore
  .eslintrc.js
  bin/run-crossbrowser-tests.sh
  bin/run-e2e-tests.sh
  package.json
  src/main/controllers/BaseSearchController.ts
  src/test/config.js
  src/test/crossbrowser/supportedBrowsers.js
  src/test/end-to-end/codecept.conf.js
  src/test/end-to-end/common/Constants.js
  src/test/end-to-end/helpers/IdamUserHelper.js
  src/test/end-to-end/helpers/JSWait.js
  src/test/end-to-end/helpers/PuppeteerHelper.js
  src/test/end-to-end/helpers/SauceLabsReportingHelper.js
  src/test/end-to-end/helpers/WebDriverHelper.js
  src/test/end-to-end/helpers/accessibility/runner.js
  src/test/end-to-end/helpers/featureToggles.js
  src/test/end-to-end/helpers/launchDarkly.js
  src/test/end-to-end/lauApi/idamHelper.js
  src/test/end-to-end/lauApi/lauHelper.js
  src/test/end-to-end/lauApi/retryHelper.js
  src/test/end-to-end/pages/IDAM/signIn.js
  src/test/end-to-end/pages/common/commonConfig.js
  src/test/end-to-end/pages/lauHomePage/caseAuditSearch.js
  src/test/end-to-end/pages/steps.js
  src/test/end-to-end/paths/homePageLau.js
  src/test/end-to-end/saucelabs.conf.js
  src/test/reporter/Report.html
  src/test/reporter/customReporter.js
  src/test/reporter/resources/angular.min.js
  src/test/reporter/resources/webfonts/fa-solid-900.woff2
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-45

#46 Revert flatpickr preload
  package.json
  src/main/views/common/webpack/css-template.njk
  src/main/views/common/webpack/css.njk
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-46

#49 LAU-351: Fix vulnerability.
  package.json
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-49
