Repository hmcts/lau-frontend, pull requests merged in 2022-10, with the labels that each got.

#85 LAU-474 Upgrade terraform version
  infrastructure/.terraform-version
  package.json
Labels: ns:lau, prd:lau, add-or-update, rel:lau-frontend-pr-85

#87 LAU-438 Uncomment case-backend in healthcheck
  package.json
  src/main/assets/js/flatpickr.ts
  src/main/modules/health/index.ts
  src/main/service/BaseService.ts
  yarn.lock
Labels: ns:lau, prd:lau, add-or-update, rel:lau-frontend-pr-87

#91 LAU-533 GOV UK Frontend Framework 4.0 Upgrade
  package.json
  src/main/assets/scss/main.scss
  webpack/govukFrontend.js
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-91

#84 LAU-473: Yarn V3 Upgrade
  .github/workflows/checks.yml
  .gitignore
  .yarn/releases/yarn-3.2.3.cjs
  .yarn/releases/yarn-3.2.4.cjs
  .yarnrc.yml
  package.json
  src/main/app.ts
  src/main/modules/nunjucks/index.ts
  src/test/end-to-end/helpers/accessibility/runner.js
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-84

#93 LAU-476 Accessibility Updates
  package.json
  src/main/views/case-activity/template.njk
  src/main/views/case-deletions/template.njk
  src/main/views/case-searches/template.njk
  src/main/views/home/template.njk
  src/main/views/logons/template.njk
  src/test/end-to-end/paths/homePageLau.js
  src/test/end-to-end/paths/logonPage.js
  src/test/unit/routes/home.test.ts
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-93

#95 LAU-536: Dependency fix.
  package.json
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-95

#97 LAU-534 Fix version data for healthcheck
  bin/githooks/pre-commit
  createVersionFile.js
  package.json
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-97

#98 LAU-288 Reorganise resource loading
  Dockerfile
  package.json
  src/main/assets/js/home.ts
  src/main/assets/scss/main.scss
  src/main/modules/health/index.ts
  src/main/views/case-activity/template.njk
  src/main/views/case-deletions/template.njk
  src/main/views/case-searches/template.njk
  src/main/views/common/template.njk
  src/main/views/common/webpack/css-template.njk
  src/main/views/common/webpack/css.njk
  src/main/views/common/webpack/js-template.njk
  src/main/views/common/webpack/js.njk
  src/main/views/logons/template.njk
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-98
