Repository hmcts/lau-frontend, pull requests merged in 2022-11, with the labels that each got.

#99 LAU-551 removing user to build image
  Dockerfile
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-99

#64 LAU-395 Add version to docker image
  docker/idam-importer/Dockerfile
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-64

#102 LAU-549 Cleanup helm release on success
  .github/PULL_REQUEST_TEMPLATE.md
  Jenkinsfile_CNP
  package.json
  src/main/models/Logs.ts
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-102
