Repository hmcts/lau-frontend, pull requests merged in 2023-06, with the labels that each got.

#147 DTSPO-13810 reschedule nightlybuilds to start at 8am
  Jenkinsfile_nightly
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-147

#150 LAU-670 Upgrade Redis cache to v6
  .gitignore
  infrastructure/main.tf
Labels: ns:lau, prd:lau, destroy, rel:lau-frontend-pr-150

#155 LAU-680 remove xml2js dependency
  package.json
  src/main/service/AuthService.ts
  src/main/views/common/webpack/css.njk
  src/main/views/common/webpack/js.njk
  yarn.lock
Labels: ns:lau, prd:lau, keep-helm, rel:lau-frontend-pr-155

#151 Back to master branch of the redis module
  infrastructure/main.tf
Labels: ns:lau, prd:lau, add-or-update, rel:lau-frontend-pr-151

#157 LAU-676 xml2js transitive dependency suppression
  yarn-audit-known-issues
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-157
