Repository hmcts/lau-frontend, pull requests merged in 2023-07, with the labels that each got.

#174 Lau 684
  charts/lau-frontend/Chart.yaml
  charts/lau-frontend/values.aat.template.yaml
  charts/lau-frontend/values.preview.template.yaml
  src/main/views/common/webpack/css.njk
  src/main/views/common/webpack/js.njk
  src/test/end-to-end/lauApi/lauHelper.js
  src/test/end-to-end/pages/IDAM/signIn.js
  src/test/end-to-end/paths/homePageLau.js
  src/test/end-to-end/paths/logonPage.js
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-174

#175 Fix dependabot version update
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-175

#176 Remove session on logout
  src/main/modules/oidc/index.ts
Labels: ns:lau, prd:lau, keep-helm, rel:lau-frontend-pr-176

#177 Remove flatpickr preload
  src/main/views/common/webpack/css-template.njk
  src/main/views/common/webpack/css.njk
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-177

#178 LAU-694: AppInsights logging fix
  charts/lau-frontend/Chart.yaml
  src/main/app.ts
  src/main/modules/appinsights/index.ts
  src/main/server.ts
  src/main/views/common/webpack/css-template.njk
  src/main/views/common/webpack/css.njk
Labels: ns:lau, prd:lau, keep-helm, rel:lau-frontend-pr-178

#182 LAU-694: Temporarily disable compression
  src/main/app.ts
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-182
