Repository hmcts/lau-frontend, pull requests merged in 2023-08, with the labels that each got.

#185 Lau 711 fix fortify scan failure
  src/test/java/build.gradle
  src/test/java/gradle/wrapper/gradle-wrapper.properties
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-185

#189 Lau 717 bump opentelemetry version
  package.json
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-189

#190 disable functional tests
  package.json
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-190

#192 disable cache due to weird browsing results
  src/main/app.ts
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-192

#193 revert back to version that has issue with azure front door
  src/main/app.ts
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-193

#195 Fix stylesheet issue
  src/main/app.ts
Labels: ns:lau, prd:lau, keep-helm, rel:lau-frontend-pr-195

#196 Unable functional tests
  package.json
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-196
