Repository hmcts/lau-frontend, pull requests merged in 2023-10, with the labels that each got.

#266 LAU-756 bump debug to 4.3.4, codeceptjs to 3.5.5
  package.json
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-266

#280 bump dependencies
  package.json
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-280

#283 update renovate to group PRs
  .github/renovate.json
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-283

#318 Migrate redis cache to Basic sku in non-prod env
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:lau, prd:lau, destroy, rel:lau-frontend-pr-318
