Repository hmcts/lau-frontend, pull requests merged in 2023-11, with the labels that each got.

#386 LAU-809 remove unused libraries
  package.json
  yarn.lock
Labels: ns:lau, prd:lau, enable_keep_helm, rel:lau-frontend-pr-386

#418 Update audit.json
  audit.json
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-418

#419 Revert audit.json
  audit.json
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-419

#400 LAU-808 logout after inactivity
  config/default.yaml
  src/main/assets/js/session-timeout.ts
  src/main/assets/scss/main.scss
  src/main/assets/scss/timeout-modal.scss
  src/main/index.ts
  src/main/modules/session/index.ts
  src/main/routes/active.ts
  src/main/routes/home.ts
  src/main/views/common/template.njk
  src/main/views/common/timeout-dialog.njk
  src/test/unit/controllers/deleted-users-search.tests.ts
  src/test/unit/controllers/logon-search.test.ts
  src/test/unit/controllers/logon.test.ts
  src/test/unit/routes/active.test.ts
  src/test/unit/routes/deletedUsers.test.ts
  src/test/unit/routes/logonAudit.test.ts
Labels: ns:lau, prd:lau, enable_keep_helm, rel:lau-frontend-pr-400
