Repository hmcts/lau-frontend, pull requests merged in 2024-08, with the labels that each got.

#729 Lau 919
  charts/lau-frontend/Chart.yaml
  charts/lau-frontend/values.aat.template.yaml
  charts/lau-frontend/values.preview.template.yaml
  charts/lau-frontend/values.yaml
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-729

#732 Lau 919
  src/main/service/CaseTypeJurisdictionAutoSuggest.ts
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-732

#724 Lau 911
  src/main/views/footer/accessibility-statement/content.ts
  src/main/views/footer/accessibility-statement/template.njk
Labels: ns:lau, prd:lau, enable_keep_helm, rel:lau-frontend-pr-724

#734 Date validation in utc
  src/main/util/Date.ts
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-734

#745 No Validation
  src/main/util/Date.ts
  src/test/unit/controllers/case-search.test.ts
  src/test/unit/controllers/deleted-users-search.tests.ts
  src/test/unit/controllers/logon-search.test.ts
  yarn-audit-known-issues
Labels: ns:lau, prd:lau, enable_keep_helm, aat/add-or-update, prod/no-changes, rel:lau-frontend-pr-745

#750 LAU-938 Info about timezone
  src/main/views/case-audit/template.njk
  src/main/views/logons/template.njk
  src/main/views/user-deletions/template.njk
Labels: ns:lau, prd:lau, enable_keep_helm, rel:lau-frontend-pr-750
