Repository hmcts/lau-frontend, pull requests merged in 2024-06, with the labels that each got.

#671 Bump versions to address CVE
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-671

#675 added csrf tokens to forms and validation endpoints
  package.json
  src/main/app.ts
  src/main/modules/csrf/index.ts
  src/main/views/case-audit/template.njk
  src/main/views/case-deletions/template.njk
  src/main/views/logons/template.njk
  src/main/views/user-deletions/template.njk
  src/test/helpers/csrf.ts
  src/test/helpers/post.ts
  src/test/helpers/roles.ts
  src/test/unit/routes/active.test.ts
  src/test/unit/routes/home.test.ts
  src/test/unit/routes/search.test.ts
  yarn.lock
Labels: ns:lau, prd:lau, enable_keep_helm, rel:lau-frontend-pr-675

#679 added extra tests and changed pa11y to use url instead of homepage
  package.json
  src/main/assets/js/flatpickr.ts
  src/main/modules/helmet/index.ts
  src/test/a11y/a11y.ts
  src/test/a11y/pa11y-config.json
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-679
