Repository hmcts/lau-frontend, pull requests merged in 2024-09, with the labels that each got.

#762 update unit test to use jest mock and validate the outcome
  src/test/unit/controllers/deleted-users.test.ts
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-762

#757 Lau 935
  config/default.yaml
  package.json
  src/main/assets/js/home.ts
  src/main/controllers/CaseChallengedAccess.controller.ts
  src/main/controllers/CaseChallengedAccessSearch.controller.ts
  src/main/models/appRequest.ts
  src/main/models/challenged-access/CaseChallengedAccessLogs.ts
  src/main/models/challenged-access/CaseChallengedAccessRequest.ts
  src/main/models/challenged-access/CaseChallengedAccesses.ts
  src/main/modules/nunjucks/index.ts
  src/main/routes/caseChallengeAccess.ts
  src/main/routes/home.ts
  src/main/routes/search.ts
  src/main/service/ChallengedAccessService.ts
  src/main/service/FeatureToggleService.ts
  src/main/views/case-challenged-access/template.njk
  src/main/views/common/navigation.njk
  src/test/data/caseChallengedAccessLogs.json
  src/test/end-to-end/common/Constants.js
  src/test/end-to-end/pages/lauHomePage/caseChallengedAccessSearch.js
  src/test/end-to-end/pages/lauHomePage/caseChallengedAccessSearchWithoutSearchData.js
  src/test/end-to-end/pages/steps.js
  src/test/end-to-end/paths/challengedSpecificAccessPage.js
  src/test/unit/controllers/case-challenged-access-search.test.ts
  src/test/unit/controllers/case-challenged-access.test.ts
  src/test/unit/controllers/deleted-users.test.ts
  src/test/unit/routes/caseChallengedAccess.test.ts
  yarn.lock
Labels: ns:lau, prd:lau, keep-helm, enable_keep_helm, rel:lau-frontend-pr-757

#771 Fix-vulnerability
  package.json
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-771

#777 LAU-962 cft-service-logs role page
  src/main/routes/home.ts
  src/main/views/case-deletions/template.njk
Labels: ns:lau, prd:lau, enable_keep_helm, rel:lau-frontend-pr-777

#786 LAU-959 enabling challended and specific tab on development
  src/main/service/FeatureToggleService.ts
  src/test/end-to-end/paths/challengedSpecificAccessPage.js
  src/test/unit/components/LaunchDarklyClient.test.ts
Labels: ns:lau, prd:lau, enable_keep_helm, rel:lau-frontend-pr-786
