Repository hmcts/lau-frontend, pull requests merged in 2024-10, with the labels that each got.

#798 cookie upgrade
  package.json
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-798

#809 Fix sonar
  src/main/components/featureToggle/LaunchDarklyClient.ts
  src/test/unit/routes/home.test.ts
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-809

#804 LAU-976
  src/main/controllers/CaseChallengedAccess.controller.ts
  src/main/models/Logs.ts
  src/main/models/challenged-access/CaseChallengedAccessLogs.ts
  src/main/util/CsvHandler.ts
  src/main/util/Date.ts
  src/main/views/case-challenged-access/template.njk
  src/test/data/caseChallengedAccessLogs.json
  src/test/unit/utils/csvHandler.test.ts
Labels: ns:lau, prd:lau, keep-helm, enable_keep_helm, aat/add-or-update, prod/add-or-update, rel:lau-frontend-pr-804

#812 Update challeged and specific access title
  src/main/views/case-challenged-access/template.njk
  src/main/views/common/navigation.njk
  src/test/end-to-end/paths/challengedSpecificAccessPage.js
Labels: ns:lau, prd:lau, keep-helm, enable_keep_helm, rel:lau-frontend-pr-812

#816 Make reason field Optional
  src/main/controllers/CaseChallengedAccess.controller.ts
Labels: ns:lau, prd:lau, enable_keep_helm, rel:lau-frontend-pr-816

#821 Added user guide PDF via an upload to github
  src/main/assets/pdfs/User Guide - Challenged and Specific Access.pdf
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-821

#822 LAU-982 Add Access request user guide
  src/main/controllers/CaseChallengedAccess.controller.ts
  src/main/views/case-challenged-access/template.njk
  src/main/views/common/access-request-results-header.njk
  webpack/app.js
Labels: ns:lau, prd:lau, enable_keep_helm, rel:lau-frontend-pr-822
