Repository hmcts/lau-frontend, pull requests merged in 2025-05, with the labels that each got.

#960 Upgrade formidable library
  package.json
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-960

#961 Lau-1133 adding dynatrace script for production
  src/main/views/common/dynatrace/head.njk
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-961

#974 CME-515 replace jitpack with azure
  src/test/java/build.gradle
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-974
