Repository hmcts/lau-frontend, pull requests merged in 2025-02, with the labels that each got.

#882 LAU-1096 remove LD log message
  src/main/components/featureToggle/LaunchDarklyClient.ts
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-882

#886 shuffle static files serve
  src/main/app.ts
  src/main/assets/scss/main.scss
Labels: ns:lau, prd:lau, enable_keep_helm, rel:lau-frontend-pr-886

#881 CME-233: terraform provider bump
  infrastructure/main.tf
Labels: ns:lau, prd:lau, enable_keep_helm, aat/add-or-update, prod/add-or-update, rel:lau-frontend-pr-881

#895 Cleanup packages
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-895

#903 Bump nodejs chart to oci
  charts/lau-frontend/Chart.yaml
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-903
