Repository hmcts/lau-frontend, pull requests merged in 2025-07, with the labels that each got.

#994 Update service navigation tab
  src/main/assets/scss/main.scss
  src/main/views/common/navigation.njk
Labels: ns:lau, prd:lau, enable_keep_helm, rel:lau-frontend-pr-994

#995 LAU-1190 - Link Opens in New Tabs Without Warning
  src/main/views/common/result-header.njk
Labels: ns:lau, prd:lau, enable_keep_helm, rel:lau-frontend-pr-995

#996 Fix dependency check
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-996

#999 Update eslint-plugin-jest
  package.json
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-999

#1001 Replace node-fetch
  package.json
  src/main/service/AuthService.ts
  src/main/service/BaseService.ts
  src/main/util/HttpResponseError.ts
  src/test/unit/utils/HttpResponseError.test.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:lau, prd:lau, enable_keep_helm, rel:lau-frontend-pr-1001

#1003 LAU-1155 Case Activity and Case search results announced
  src/main/assets/js/home.ts
  src/main/views/case-audit/template.njk
  src/main/views/case-challenged-access/template.njk
  src/main/views/case-deletions/template.njk
  src/main/views/logons/template.njk
  src/main/views/user-deletions/template.njk
Labels: ns:lau, prd:lau, enable_keep_helm, rel:lau-frontend-pr-1003
