Repository hmcts/lau-frontend, pull requests merged in 2025-03, with the labels that each got.

#891 LAU-918 enable appinsights early
  charts/lau-frontend/Chart.yaml
  package.json
  src/main/app.ts
  src/main/controllers/BaseSearchController.ts
  src/main/controllers/CaseActivity.controller.ts
  src/main/controllers/CaseChallengedAccess.controller.ts
  src/main/controllers/CaseChallengedAccessSearch.controller.ts
  src/main/controllers/CaseDeletions.controller.ts
  src/main/controllers/CaseDeletionsSearch.controller.ts
  src/main/controllers/CaseSearch.controller.ts
  src/main/controllers/CaseSearches.controller.ts
  src/main/controllers/DeletedUsers.controller.ts
  src/main/controllers/DeletedUsersSearch.controller.ts
  src/main/controllers/Logon.controller.ts
  src/main/controllers/LogonSearch.controller.ts
  src/main/models/appRequest.ts
  src/main/modules/appinsights/index.ts
  src/main/modules/health/index.ts
  src/main/modules/logging/index.ts
  src/main/modules/properties-volume/index.ts
  src/main/modules/session/index.ts
  src/main/server.ts
  src/main/service/AuthService.ts
  src/main/service/BaseService.ts
  src/main/service/CaseService.ts
  src/main/service/CaseTypeJurisdictionAutoSuggest.ts
  src/main/service/ChallengedAccessService.ts
  src/main/service/DeletedUsersService.ts
  src/main/service/LogonService.ts
  src/main/types/@hmcts/nodejs-logging.d.ts
  src/test/end-to-end/helpers/IdamUserHelper.js
  src/test/end-to-end/helpers/featureToggles.js
  src/test/end-to-end/lauApi/lauHelper.js
  src/test/end-to-end/logger.js
  src/test/end-to-end/paths/challengedSpecificAccessPage.js
  src/test/end-to-end/paths/deletedUserPage.js
  src/test/end-to-end/paths/homePageLau.js
  src/test/end-to-end/paths/logonPage.js
  yarn.lock
Labels: ns:lau, prd:lau, enable_keep_helm, aat/add-or-update, prod/no-changes, rel:lau-frontend-pr-891

#913 Bump glob library
  package.json
  src/main/app.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-913

#915 LAU-1125 remove unused feature
  src/test/end-to-end/helpers/JSWait.js
  src/test/reporter/Report.html
  src/test/reporter/customReporter.js
  src/test/reporter/resources/angular.min.js
  src/test/reporter/resources/webfonts/fa-solid-900.woff2
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-915

#916 LAU-1125 bump fortify
  src/test/java/build.gradle
  src/test/java/gradle/wrapper/gradle-wrapper.jar
  src/test/java/gradle/wrapper/gradle-wrapper.properties
  src/test/java/gradlew
  src/test/java/gradlew.bat
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-916

#921 Lau-1128 revert nock library to 13.0.4
  package.json
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-921

#924 LAU-1130 do not pass _csrf token to java backends
  src/main/service/BaseService.ts
  src/test/end-to-end/helpers/JSWait.js
  src/test/end-to-end/helpers/accessibility/runner.js
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-924

#928 lau-fortify-upgrade
  src/test/java/build.gradle
Labels: ns:lau, prd:lau, rel:lau-frontend-pr-928
